// Auto generated by Craby. DO NOT EDIT.
#pragma once

#include "CrabyUtils.hpp"
#include "ffi.rs.h"
#include <ReactCommon/TurboModule.h>
#include <jsi/jsi.h>
#include <memory>

namespace craby {
namespace crabykv {

class JSI_EXPORT CxxCrabyKvModule : public facebook::react::TurboModule {
public:
  static constexpr const char *kModuleName = "CrabyKv";
  static std::string dataPath;

  CxxCrabyKvModule(std::shared_ptr<facebook::react::CallInvoker> jsInvoker);
  ~CxxCrabyKvModule();

  void invalidate();
  static facebook::jsi::Value
  clear(facebook::jsi::Runtime &rt,
      facebook::react::TurboModule &turboModule,
      const facebook::jsi::Value args[], size_t count);

  static facebook::jsi::Value
  contains(facebook::jsi::Runtime &rt,
      facebook::react::TurboModule &turboModule,
      const facebook::jsi::Value args[], size_t count);

  static facebook::jsi::Value
  get(facebook::jsi::Runtime &rt,
      facebook::react::TurboModule &turboModule,
      const facebook::jsi::Value args[], size_t count);

  static facebook::jsi::Value
  initialize(facebook::jsi::Runtime &rt,
      facebook::react::TurboModule &turboModule,
      const facebook::jsi::Value args[], size_t count);

  static facebook::jsi::Value
  keys(facebook::jsi::Runtime &rt,
      facebook::react::TurboModule &turboModule,
      const facebook::jsi::Value args[], size_t count);

  static facebook::jsi::Value
  remove(facebook::jsi::Runtime &rt,
      facebook::react::TurboModule &turboModule,
      const facebook::jsi::Value args[], size_t count);

  static facebook::jsi::Value
  set(facebook::jsi::Runtime &rt,
      facebook::react::TurboModule &turboModule,
      const facebook::jsi::Value args[], size_t count);

  static facebook::jsi::Value
  size(facebook::jsi::Runtime &rt,
      facebook::react::TurboModule &turboModule,
      const facebook::jsi::Value args[], size_t count);

protected:
  std::shared_ptr<facebook::react::CallInvoker> callInvoker_;
  std::shared_ptr<craby::bridging::CrabyKv> module_;
  std::atomic<bool> invalidated_{false};
  std::atomic<size_t> nextListenerId_{0};
  std::mutex listenersMutex_;
  std::unordered_map<
    std::string,
    std::unordered_map<size_t, std::shared_ptr<facebook::jsi::Function>>>
    listenersMap_;
  std::shared_ptr<craby::utils::ThreadPool> threadPool_;
};

} // namespace crabykv
} // namespace craby
