// Auto generated by Craby. DO NOT EDIT.
#[rustfmt::skip]
use craby::prelude::*;

use crate::craby_kv_impl::*;
use crate::generated::*;

use bridging::*;

#[cxx::bridge(namespace = "craby::crabykv::bridging")]
pub mod bridging {
    struct NullableString {
        null: bool,
        val: String,
    }



    extern "Rust" {
        type CrabyKv;

        #[cxx_name = "createCrabyKv"]
        fn create_craby_kv(id: usize, data_path: &str) -> Box<CrabyKv>;

        #[cxx_name = "clear"]
        fn craby_kv_clear(it_: &mut CrabyKv) -> Result<()>;

        #[cxx_name = "contains"]
        fn craby_kv_contains(it_: &mut CrabyKv, key: &str) -> Result<bool>;

        #[cxx_name = "get"]
        fn craby_kv_get(it_: &mut CrabyKv, key: &str) -> Result<NullableString>;

        #[cxx_name = "initialize"]
        fn craby_kv_initialize(it_: &mut CrabyKv) -> Result<()>;

        #[cxx_name = "keys"]
        fn craby_kv_keys(it_: &mut CrabyKv) -> Result<Vec<String>>;

        #[cxx_name = "remove"]
        fn craby_kv_remove(it_: &mut CrabyKv, key: &str) -> Result<()>;

        #[cxx_name = "set"]
        fn craby_kv_set(it_: &mut CrabyKv, key: &str, value: &str) -> Result<()>;

        #[cxx_name = "size"]
        fn craby_kv_size(it_: &mut CrabyKv) -> Result<f64>;
    }

}

fn create_craby_kv(id: usize, data_path: &str) -> Box<CrabyKv> {
    let ctx = Context::new(id, data_path);
    Box::new(CrabyKv::new(ctx))
}

fn craby_kv_clear(it_: &mut CrabyKv) -> Result<(), anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.clear();
        ret
    })
}

fn craby_kv_contains(it_: &mut CrabyKv, key: &str) -> Result<bool, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.contains(key);
        ret
    })
}

fn craby_kv_get(it_: &mut CrabyKv, key: &str) -> Result<NullableString, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.get(key);
        ret.into()
    })
}

fn craby_kv_initialize(it_: &mut CrabyKv) -> Result<(), anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.initialize();
        ret
    })
}

fn craby_kv_keys(it_: &mut CrabyKv) -> Result<Vec<String>, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.keys();
        ret
    })
}

fn craby_kv_remove(it_: &mut CrabyKv, key: &str) -> Result<(), anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.remove(key);
        ret
    })
}

fn craby_kv_set(it_: &mut CrabyKv, key: &str, value: &str) -> Result<(), anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.set(key, value);
        ret
    })
}

fn craby_kv_size(it_: &mut CrabyKv) -> Result<f64, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.size();
        ret
    })
}
