// Auto generated by Craby. DO NOT EDIT.
// Hash: e82df54823e2a5aa
#[rustfmt::skip]
use crate::ffi::bridging::*;
use crate::context::*;
use crate::types::*;

pub trait CrabyKvSpec {
    fn new(ctx: Context) -> Self;
    fn id(&self) -> usize;
    fn clear(&mut self) -> Void;
    fn contains(&mut self, key: &str) -> Boolean;
    fn get(&mut self, key: &str) -> Nullable<String>;
    fn initialize(&mut self) -> Void;
    fn keys(&mut self) -> Array<String>;
    fn remove(&mut self, key: &str) -> Void;
    fn set(&mut self, key: &str, value: &str) -> Void;
    fn size(&mut self) -> Number;
}

impl Default for NullableString {
    fn default() -> Self {
        NullableString {
            null: true,
            val: String::default(),
        }
    }
}

impl From<NullableString> for Nullable<String> {
    fn from(val: NullableString) -> Self {
        Nullable::new(if val.null { None } else { Some(val.val) })
    }
}

impl From<Nullable<String>> for NullableString {
    fn from(val: Nullable<String>) -> Self {
        let val = val.into_value();
        let null = val.is_none();
        NullableString {
            val: val.unwrap_or(String::default()),
            null,
        }
    }
}
