// Auto generated by Craby. DO NOT EDIT.
#include <CxxCrabyKvModule.hpp>
#include <ReactCommon/CxxTurboModuleUtils.h>
#include <jni.h>

jint JNI_OnLoad(JavaVM *vm, void *reserved) {
  facebook::react::registerCxxModuleToGlobalModuleMap(
    craby::crabykv::modules::CxxCrabyKvModule::kModuleName,
    [](std::shared_ptr<facebook::react::CallInvoker> jsInvoker) {
      return std::make_shared<craby::crabykv::modules::CxxCrabyKvModule>(jsInvoker);
    });
  return JNI_VERSION_1_6;
}

extern "C"
JNIEXPORT void JNICALL
Java_rs_craby_crabykv_CrabyKvPackage_nativeSetDataPath(JNIEnv *env, jclass clazz, jstring jDataPath) {
  auto dataPath = std::string(env->GetStringUTFChars(jDataPath, nullptr));
  craby::crabykv::modules::CxxCrabyKvModule::dataPath = dataPath;
}
